### ISSUE TITLE
Max width not displaying correctly 

### ISSUE THREAD

**Issue by frogsicle** [gglyptodon/dinomite#17]
On a pixel 6a screen the maximum width does not display correctly. See attached, that's as far as I can scroll to the left. 

And thanks, this game is the best!!!

![Screenshot_20241121-224920](https://github.com/user-attachments/assets/b0f8c8be-3cf3-49bc-9f15-d41a3b284dfb)

**Comment by gglyptodon** [comment]
Thank you for the bug report. The issue should be resolved, please let me know if you notice any persisting problems

**Comment by frogsicle** [comment]
Works great. Thank you!
